couchbase/couchbase-lite-net

src/Couchbase.Lite.Shared/Manager.cs
This is my official first pull request on an open source project, so let me know if I'm doing something stupid.
This patch is for #364 which allows cblite to function in a .NET web app hosted in Azure.  By enabling the .NET API to working in Azure, we are able to much more quickly generate initial snapshots of databases for mobile clients (as opposed to waiting for hundreds of thousands of records to stream down).
=> Fix: Manager static ctor crashes on Azure #364

src/Couchbase.Lite.Shared/Util/CookieStore.cs
This fixes a null reference exception I encountered when using CBL from
my own .Net45 unit tests.  I was getting a null reference exception when
setting the replicator cookies.  The CBL unit test for adding/deleting
cookies seems to work fine without this though.
=> Fix null reference exception when setting cookie

src/Couchbase.Lite.Unity/UnityLogger.cs
Current logging functions LogFormat, LogWarningFormat, LogErrorFormat, are only available from Unity 5.0. This gives cross compile errors when trying to build for iOS, if Unity version is 4.x. Since many projects are still using Unity 4.x, it seems better to use the original logging API.
=> Unity 4.6 compatible logging

src/Couchbase.Lite.Shared/Replication/MultipartDocumentReader.cs
It should have been checking for the MD5 hash as a fallback as opposed to checking for the SHA1 hash twice.
=> MD5 hash wasn't being checked.

src/Couchbase.Lite.Shared/Database.cs
This property is mentioned in the [docs](http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/database/index.html) as public API:
*You can tune the maximum revision tree depth parameter (the Database object's maxRevTreeDepth property). This governs how old a revision must be before its metadata is discarded. It defaults to 20, meaning that each document will remember the history of its latest 20 revisions. Setting this to a smaller value will save storage space, but can result in spurious conflicts if clients are making lots of offline changes and then sync.*
=> Make MaxRevTreeDepth a public Property like specified in the docs

src/Couchbase.Lite.Shared/Revisions/RevisionInternal.cs, src/Couchbase.Lite.Tests.Shared/RevisionsTest.cs
This handles the case where _deleted is set to either null or a non-boolean type in the JSON.  Addresses issue #414.
=> Added bool type checking to the RevisionInternal constructor.  

src/Couchbase.Lite.Shared/Replication/Pusher.cs
If the content type has not explicitly been set an exception will be thrown when the pusher runs because null is not a valid media type header value.
=> Media type header value cannot be null.

src/Couchbase.Lite.Shared/Replication/Puller.cs, src/Couchbase.Lite.Shared/Store/BlobKey.cs, src/Couchbase.Lite.Shared/Store/SqliteCouchStore.cs, src/Couchbase.Lite.Tests.Shared/AttachmentsTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
Fixes a bug where if the puller pulls two new revisions at once, one will be added as a stub in addition to the real one since both will run in a transaction and the logic for finding history was transaction isolated.
Fixes a possible race condition on the changeTracker variable in Puller whereby it will be set to null after a null check by another thread.
=> Fixes #442

src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems, src/Couchbase.Lite.Shared/Store/SqliteViewStore.cs, src/Couchbase.Lite.Shared/View.cs, src/Couchbase.Lite.Shared/View/IViewStore.cs, src/Couchbase.Lite.Shared/View/UpdateJob.cs, src/Couchbase.Lite.Tests.Shared/ViewsTest.cs
i.e. to record which updates are in progress and doesn't duplicate them, instead waiting for the original work to finish and using its results.  Closes issue #430.
=> Refactored the UpdateIndex method to use logical coalescing

src/Couchbase.Lite.Shared/Store/SqliteViewStore.cs, src/Couchbase.Lite.Tests.Shared/ViewsTest.cs
When querying a map-only view for a specific set of keys, where the keys of the view are arrays, no results are being returned.
The problem occurs when sorting the results in the same order as the keys given to the query. The results are grouped together by key by adding them to a `Dictionary<object, List<QueryRow>>`. However, keys which are arrays are returned as `JArray`, which needs to use `JTokenEqualityComparer` to be used as a `Dictionary` key.
This solution simply converts the keys to JSON strings before adding to and retrieving from the `Dictionary`.
The test was taken from the Android project:
https://github.com/couchbase/couchbase-lite-android/tree/36b977c7389aaebf466229b198784363d7b7cef9/src/androidTest/java/com/couchbase/lite/ViewsTest.java#L583
=> Fix querying for keys which are arrays

src/Couchbase.Lite.Shared/View/UpdateJob.cs
My project makes heavy use of asynchronous queries, and I was occasionally seeing a deadlock of the Manager's workExecutor. 
I did some digging and found that the UpdateJob task continuation was not always being executed, even though the task ran to completion. If another UpdateIndex operation was queued and the previous continuation did not execute, the View would end up waiting forever for the new operation to complete. 
Scheduling the continuation on TaskScheduler.Default ensures the continuation is always executed.
=> Fix deadlock when multiple UpdateIndex operations are queued

src/Couchbase.Lite.Shared/Exceptions/CouchbaseLiteException.cs
Both a bad practice (see "CLR Via CSharp") and also required for UWP.
=> Change CouchbaseLiteException to inherit from Exception

src/ListenerComponent/Couchbase.Lite.Listener.Shared/PeerToPeer/CouchbaseLiteResponse.cs, src/ListenerComponent/Couchbase.Lite.Listener.Shared/PeerToPeer/DBMonitorCouchbaseResponseState.cs, src/ListenerComponent/Couchbase.Lite.Listener.Shared/PeerToPeer/DatabaseMethods.cs
There is a race between when detecting the need to listen to the database for changes on a continuous changes feed and the start of the changes feed in which a change can slip in undetected.  Need to be sure that it is not skipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/786)
=> Fixes #767

src/Couchbase.Lite.Shared/Manager/NetworkReachabilityManager.cs, src/Couchbase.Lite.Shared/Replication/WebSocketChangeTracker.cs
If a user has a proxy, TcpClient() by default doesn't take that into account.
Same with the WebSocket class in websocket-sharp, which I believe actually uses TcpClient(), but they have a way to set a proxy.
I'm on .NET version 4.5, but according to documentation, the properties used, such as WebRequest.DefaultWebProxy, Uri.DnsSafeHost has been available since at least .NET 2.0
https://msdn.microsoft.com/en-us/library/system.net.webrequest.defaultwebproxy(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.uri.dnssafehost(v=vs.90).aspx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/799)
=> Added support to use default system proxy

src/StorageEngines/ForestDB/storage.forestdb.shared/src/ForestDBCouchStore.cs, src/StorageEngines/SQLiteCommon/storage.sqlite.common/src/SqliteCouchStore.cs
Delay encoding the JSON until after we know whether or not this insertion is on top of a deletion.  On ForestDB this is awkward and requires an extra read, unless there is a better way that I missed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/790)
=> Fixes #749

src/Couchbase.Lite/API/Document/Document.cs
Fixed memory leak caused when updating documents with new information.  The old lite-core document was never released from memory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/913)
=> Fixed memory leak. Fixes #912

src/Couchbase.Lite.Shared/Document/DataOps.cs
- "Blob or" currently displays as "Blobor"
- Add oxford coma after "Blob"
- Remove extra space after end of first sentence
=> Fix spacing in exception message

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
Replication eventing: update the document ended listener name to AddDocumentReplicationListener and use RemoveChangeListener to remove both/either ChangeListener & DocumentReplicationListener
Replication filters:  update LiteCore, update C4ReplicatorFilterFunction name to C4ReplicatorValidationFunction, add ReplicationFilter class which contains Document and IsDeleted properties, add C4RevisionFlags parameter in filter callback function, add push replication with deleted document test
=> API update for replication eventing

src/Couchbase.Lite.Shared/API/Sync/ReplicatorProgress.cs
#1100 Override ToString method in ReplicatedDocument class. This will help QA to print out the debug info easily.
=> Override ToString method in ReplicatedDocument class.

src/LiteCore/parse/templates_c4/C4ReplicatorParameters.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_defs.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
LiteCore added a new Boolean variable dontStart in C4ReplicatorParameters and c4repl_start method, so updated bindings and generated the bindings in .Net. And update LiteCore.
=> LiteCore updates 

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
Fixes CBL-349 by catching exception when running conflictResolver.Resolve failed. Also fix unit test TestNonBlockingDatabaseOperationConflictResolver.
=> CBL-349 Catching exception thrown when conflictResolver.Resolve failed

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/Support/Status.cs
Fixes CBL-326 by adding SocketError.NetworkDown case in ConvertNetworkError method so it can be translated into what LiteCore expects. Also add an error check before go into IsPermanentError to save some process time.
=> Fixes CBL-326 by adding SocketError.NetworkDown case

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs
CBL-456 Set the level on Log.Console and then set the domains according to what is included in the passed enum.
=> CBL-456 Set the level on Log.Console 

src/Couchbase.Lite.Shared/Support/Status.cs
CBL-489 Instead of throwing .Net Error code, throw posix error and code in order to get the correct transient behavior...
=> CBL-489 Throw posix error and code instead of .Net error code

README.md
When I clicked the link to the official documentation, it took me to this page:
* https://docs.couchbase.com/couchbase-lite/2.0/index.html
... which notifies the user that a newer version of the document is available.
---
This PR replaces the old link with the newer link:
* https://docs.couchbase.com/couchbase-lite/current/index.html
=> Update link to official documentation

src/Couchbase.Lite.Shared/API/Document/MutableDictionaryObject.cs, src/Couchbase.Lite.Shared/Serialization/FleeceMutableArray.cs, src/Couchbase.Lite.Shared/Serialization/MValue.cs, src/Couchbase.Lite.Tests.Shared/DocumentTest.cs
CBL-1077 Fix fleece mutable array encoding by directly encode the item.
MValue has its own FLEncode method, which checks both value and nativeValue (if value is non-null, it writes it using FLEncoder_WriteValue)
=> CBL-1077 Null values are returned from Document GetArray method fix

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/Sync/ReplicatorOptionsDictionary.cs
Instead just send a token for it to claim later.  This avoids logging sensitive information as well because all that will be logged is a memory address pointing to a handle to a .NET object.
=> Don't send the client certificate data to LiteCore

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/P2PTest.cs, src/Couchbase.Lite.Tests.Shared/Util/MockConnection.cs
CBL-1192
This was causing P2P test hanging because the new Core behavior performs the start logic asynchronously, meaning that the mock side needs to wait for both sides to be finished opening before doing anything else.
=> CBL-1192 Fix some flaky logic in MockConnection

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
CBL-1217 Check Database is open before proceeding getting pending doc ids and check is doc pending. Add unit tests to verify.
=> CBL-1217 Check database is open in the beginning of pending doc id API

src/Couchbase.Lite.Shared/API/Sync/BasicAuthenticator.cs, src/Couchbase.Lite.Shared/Sync/AuthOptionsDictionary.cs, src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs, src/LiteCore/src/LiteCore.Shared/Interop/Fleece.cs
Only convert the SecurityString to string in fleece encoding and password into NetworkCredential.
=> Use SecurityString in password securely. 

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
CBL-951 Add close/delete database tests in url endpoint listener. Also add unit test case that is added in iOS.
=> CBL-951 Add database delete/close tests in URL Endpoint Listener, TestClientCertAuthRootCertsError, and code clean up.

src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
CBL-1476 Check if proxy server address is not IPAddress, then just past server host string into client connect async method.
=> CBL-1476 Add DNS support in proxy server address

src/build/do_build.ps1
VS 2019 no longer has the same reg key entry as VS2017.  We should use "Get-CimInstance MSFT_VSInstance" instead.
-Ming Ho
=> CBD-4039, switch to check for vs 2019 installation.

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/BlobTest.cs, src/Couchbase.Lite.Tests.Shared/DatabaseEncryptionTest.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/Couchbase.Lite.Tests.Shared/DocumentTest.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Database_native.cs, src/LiteCore/test/LiteCore.Tests.Shared/DatabaseTest.cs
CBL-1843 Remove deprecated ResetCheckpoint()
Replace c4db_purgeExpiredDocs with c4db_startHousekeeping (Note: Set doc expired now actually delayed a little compare with old API call)
Remove SetLogLevel and Compact deprecated methods from Database. Update tests.
=> CBL-1843 Remove deprecated APIs

src/Couchbase.Lite.Shared/API/Error/CouchbaseLiteErrorMessage.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs, src/Couchbase.Lite.Shared/Sync/ReplicatorOptionsDictionary.cs, src/Couchbase.Lite.Tests.Shared/P2PTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
If replicator config option for heartbeat and retry did not get key/value from LiteCore, assign -1.
Returns default values 0 for MaxAttempts when actual default value 10 for a single shot replicator or max int for a continuous replicator is applied in LiteCore. (This part is the most confusing part and I added some bullet points notes.)
=> Revise Heartbeat and Retry logic

src/Couchbase.Lite.Shared/API/Query/FullTextExpression.cs, src/Couchbase.Lite.Shared/API/Query/FullTextFunction.cs, src/Couchbase.Lite.Shared/API/Query/IExpression.cs, src/Couchbase.Lite.Shared/API/Query/IFullTextExpression.cs, src/Couchbase.Lite.Shared/Query/QueryExpression.cs, src/Couchbase.Lite.Shared/Query/QueryUnaryExpression.cs, src/Couchbase.Lite.Tests.Shared/DatabaseEncryptionTest.cs, src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
1. FTS Match Functions
- Deprecate FullTextExpression class and it's Index Match full text expression,  IFullTextExpression.
- Add Index name Match query expression function in FullTextFunction class.
- Update tests
2. isValued and isNotValued operator
- Deprecate IsNullOrMissing and NotNullOrMissing from QueryExpression and IExpression.
- Add IsValued and IsNotValued in QueryExpression and IExpression.
- Update tests
=> CBL-1793 Change to QueryBuilder API

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Query/FullTextIndexConfiguration.cs, src/Couchbase.Lite.Shared/API/Query/ValueIndexConfiguration.cs, src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems, src/Couchbase.Lite.Shared/Query/IndexConfiguration.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Index_native.cs, src/LiteCore/test/LiteCore.Tests.Shared/QueryTest.cs
- Use new c4db_createIndex2 instead of c4db_createIndex
- Add CreateIndex method takes IndexConfiguration as parameter in Database class
- Add ValueIndexConfiguration class and FullTextIndexConfiguration
- Update LiteCore to Commit: 63d918b967dbf9170c970381a3eacd9f4eef2a33 [63d918b] (Add the capability of createIndex to take index expression in N1QL)
=> CBL-1790 Create Query Index with N1QL string array

src/Couchbase.Lite.Shared/API/Document/ArrayObject.cs, src/Couchbase.Lite.Shared/Serialization/FleeceMutableArray.cs, src/Couchbase.Lite.Tests.Shared/BlobTest.cs
Revert using FLSlotSet in FleeceMutableArray to prevent memory leak when calling MutableArrayObject.AddBlob while the Blob Content is large in size.
=> CBL-2102 Fix memory leak during MutableArrayObject.AddBlob while the Blob Content is large in size

src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Base_native.cs
CBL-2120
Retain c4socket when WebSocket starts and a release c4socket after c4socket is closed.
Add more logging c4socket activities.
=> CBL-2120 [hydrogen] Retain c4socket when WebSocket starts and a release c4socket after c4socket is closed

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
Return null when user pass an empty string doc id into Database.GetDocument(id)
=> CBL-2251 Database.GetDocument("") returns null

src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Database/Scope.cs, src/Couchbase.Lite.Shared/Query/QueryResultContext.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
Database close/delete handling within new Scopes Collections implementation
Dev tests:
- Use Collection APIs on Deleted Collection
- Use Collection API on Closed or Deleted Database
- Use Scope API on Closed or Deleted Database
- Get Scopes or Collections on Closed or Deleted Database
- Use Database API when the Default Collection is Deleted
- Use Scope API when No Collections in the Scope
=> CBL-3235 Database close/delete handling within new Scopes Collections implementation

src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Database/Scope.cs, src/Couchbase.Lite.Shared/API/Document/ArrayObject.cs, src/Couchbase.Lite.Shared/API/Document/DictionaryObject.cs, src/Couchbase.Lite.Shared/API/Document/Document.cs, src/Couchbase.Lite.Shared/Document/DocContext.cs, src/Couchbase.Lite.Shared/Query/QueryResultContext.cs, src/Couchbase.Lite.Shared/Query/QueryResultSet.cs, src/Couchbase.Lite.Shared/Serialization/FLValueConverter.cs, src/Couchbase.Lite.Tests.Shared/CSharpTest.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
- Optimize the get collection logic to use cache and collection is valid LiteCore check.
- Return get collection null instead of throw in case of collection is not valid base on API spec.
- Remove has collection LiteCore check since it's replaced with collection is valid which is less expensive.
- Enable the tests that were disabled awaiting for the LiteCore fixes that now are in
- Revert the source change to take database as parameter instead of collection for query related items.
=> CBL-3334 Get Collection update & Enable the tests that were disabled awaiting for the LiteCore fixes that now are in

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4ReplicatorTypes_defs.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
- Update LiteCore to Commit: 7956e05736408e28d0116ecd2eb37f06c3a0a6a9 [7956e05] (CBL-3349 : getPendingDocIDs and isDocumentPending to have collection as argument)
- Update C# LiteCore bindings for replicator in scopes collections
- Add back Replicator, P2P, and URLEndpointListener tests which all should work with default collection(s) now
=> CBL-3342 Update LiteCore and bindings for replicator in scopes collections

src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Shared/API/Database/Scope.cs, src/Couchbase.Lite.Shared/API/Error/CouchbaseLiteErrorMessage.cs
Platforms decided to have the same error message for C4ErrorCode.NotOpen. I want to add an inner exception with a more detailed error message for the reason of getting C4ErrorCode.NotOpen.
=> CBL-3417 Update message for C4ErrorCode.NotOpen

src/Couchbase.Lite.Shared/API/DI/Service.cs, src/Couchbase.Lite.Shared/Support/Android/AndroidConsoleLogger.cs, src/Couchbase.Lite.Shared/Support/Android/MainThreadTaskScheduler.cs, src/Couchbase.Lite.Shared/Support/Android/XamarinAndroidProxy.cs, src/Couchbase.Lite.Shared/Support/netdesktop/DesktopConsoleLogger.cs, src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj, src/Couchbase.Lite.Support.Android/Properties/AssemblyInfo.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs, src/Couchbase.Lite.Tests.Shared/MigrationTest.cs, src/Couchbase.Lite.Tests.Shared/PerfTest.cs, src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs, src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/Util/ZipFileExtensions.cs, src/LiteCore/test/LiteCore.Tests.Shared/Test.cs
All the changes in this PR is to make the Maui android test project build and able to use CBL libraries.
Some methods use in the tests are disabled due to incompatibility with .Net 6 Android/Maui Android and it requires time to research and investigate.
[CBL-3711](https://issues.couchbase.com/browse/CBL-3711) is created for the job.
And there also some indentation update in this PR.
=> CBL-3628 Maui test project to include Android platform

packaging/nuget/couchbase-lite-support-android.nuspec, packaging/nuget/couchbase-lite-support-ios.nuspec, packaging/nuget/couchbase-lite.nuspec, src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj, src/Couchbase.Lite.Support.Apple/iOS/Couchbase.Lite.Support.iOS.csproj, src/Couchbase.Lite/Couchbase.Lite.csproj
Revert to include target framework version for .Net 6 iOS/Android in csprojs and nuspec files to fix Nuget error: Some included files are included under TFMs which are missing a platform version: net6.0-android... (Tested with the changes and verified working)
EE branch: https://github.com/couchbaselabs/couchbase-lite-net-ee/tree/PR-1451
=> Add AddTargetPlatformVersion attributes in Couchbase Lite, Support Android and Support iOS projects

src/Couchbase.Lite.Support.WinUI/Couchbase.Lite.Support.WinUI.csproj
Fix CI build in packaging stage (winui)
https://mobile.jenkins.couchbase.com/blue/organizations/jenkins/couchbase-lite-net-edition-build/detail/couchbase-lite-net-edition-build/3292/pipeline
=> No need to check Platform when including LiteCore libs in Packaging Config

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
CBL-3947 Test to verify GCLB Cookies work
Piggy back this PR to remove none applicable comments (ex. Note: the default collection can be deleted but cannot be recreated.) due to CBL-3982 update
=> CBL-3947 Test to verify GCLB Cookies work

packaging/nuget/couchbase-lite.nuspec, src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems, src/Couchbase.Lite.Shared/Support/Android/XEReachability.cs, src/Couchbase.Lite/Couchbase.Lite.csproj
To work around a bug with NetworkAddressChanged in which socket fds are not correctly freed by mono
Companion PR: https://github.com/couchbaselabs/couchbase-lite-net-ee/pull/97
=> CBL-4133: Rewrite Xamarin Android reachability class to use Xamarin Essentials

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs, src/Couchbase.Lite.Shared/Sync/ReplicatorOptionsDictionary.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
For example, foo.bar.com could set a cookie for all of bar.com, which is normally disallowed for security reasons.
=> CBL-4142: Add option to allow save of parent domain cookies

Jenkinsfile, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj, src/Couchbase.Lite.Support.Apple/iOS/Couchbase.Lite.Support.iOS.csproj, src/Couchbase.Lite.Support.Apple/iOS/ios.targets, src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj, src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.shproj, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/LiteCore/test/LiteCore.Tests.Shared/LiteCore.Tests.Shared.shproj, src/build/do_fetch_litecore.ps1, src/global.json
The main components here are to make the necessary changes (which were a lot both in core and .NET) for Mac Catalyst to function (all tests have passed locally).  Since PR validation is so out of control, this PR also removes the dropped platform .NET Core 3.1 from the testing, as well as the technically unsupported .NET Core / .NET 6 mac desktop.  Xamarin is dropping from validation testing in favor of MAUI.  The rest is just packaging and/or testing changes needed to accommodate Mac Catalyst.
=> CBL-4108 Update MacCatalyst test

src/Couchbase.Lite/Couchbase.Lite.csproj
Use the same version as the one in the target framework
```
/usr/local/share/dotnet/packs/Microsoft.MacCatalyst.Sdk/16.2.3/tools/msbuild/iOS/Xamarin.Shared.targets(532,3): error : Could not map the Mac Catalyst version 10.15 to a corresponding macOS version. Valid Mac Catalyst versions are: 15.0, 13.3.1, 16.2, 14.3, 15.5, 13.1, 16.0, 14.1, 15.3, 14.6, 13.4, 15.6, 13.2, 14.4, 16.1, 14.2, 15.4, 13.5, 14.7, 15.2, 14.0, 13.3, 14.5 [/Users/andoni/git/couchbase-lite-net/src/Couchbase.Lite/Couchbase.Lite.csproj::TargetFramework=net6.0-maccatalyst14.2]
```
=> maccatalyst: fix dotnet build with a valid SupportedOSPlatformVersion

src/build/do_build.ps1, src/build/do_fetch_litecore.ps1
Remove hard coded paths to python / deactivate
Remove the LiteCore.xcframework path each time since Windows has such a hard time dealing with overwrites, especially when symbolic links are involved
=> Fix up some build related stuff

packaging/nuget/couchbase-lite-support-ios.nuspec, src/Couchbase.Lite.Shared/API/Info/Defaults.cs, src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj, src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj, src/build/do_build.ps1
LiteCore.framework -> LiteCore.xcframework
net6.0-android31.0 -> net6.0-android31
Condition for copying LiteCore.dll
=> Fix some packaging typos

src/Couchbase.Lite.Tests.Android/Properties/AndroidManifest.xml, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/Couchbase.Lite.Tests.UWP/Couchbase.Lite.Tests.UWP.csproj
LiteCore 3.1.0-341
Need to use the non hardcoded version of EADDRINUSE for Xamarin (both iOS and Android define \_\_MOBILE\_\_) UWP somehow is missing the C# latest version attribute (the default is 7.3, which doesn't support some of the testing code)
=> Fix a test error, UWP csproj missing attribute, and bump LiteCore

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Database.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
This is tough to explain, but the lifetime management of the various interop objects was a bit sketchy and somehow, only in .NET Native, this caused push and/or pull filter functions defined by C# to become invalid (GC?  Memory move?) which meant that when LiteCore tried to call them it would get an unrecoverable native exception.  This PR creates a better hierarchy of objects that can have lifetimes tied to their parents.
There was also a few other issues found during this investigation dealing with tests.  The NonBlockingDatabaseOperation test was always throwing an exception and never actually verifying anything (the exception would kill the background thread and go unnoticed) and the "forum" test appears to not actually do anything and so it was removed.
=> Fix UWP tests crashing when built with .NET Native

packaging/nuget/couchbase-lite-support-ios.nuspec, src/build/do_build.ps1, src/build/do_fetch_litecore.ps1
There is no way to sanely package an xcframework for mac inside of a nuget package EXCEPT to include it directly as a zip (see https://github.com/NuGet/Home/issues/10734 )
So now the process when building the product is to:
1. Download the LiteCore.xcframework zip
2. Extract it, and leave the zip in place
3. Copy ONLY the ios sim and ios devices slice into the package for Xamarin iOS
4. Copy the zip into the runtimes/ios/native portion of the package so that .NET 6 iOS and Mac Catalyst will consume it
=> Redo Mac Catalyst packaging again

src/Couchbase.Lite.Tests.Shared/ConcurrencyTest.cs, src/Couchbase.Lite.Tests.Shared/Util/WaitAssert.cs
The synchronization context of the runtime is different than the others which seems to cause a deadlock when running WaitAssert.RunAssertAsync without using `ConfigureAwait(false)`
=> Fix ConcurrencyTests hanging on .NET 6 iOS

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/P2PTest.cs
Previous code used to skip the conflict task check if there was no recorded error.  This seems like a meaningless check, so remove it and always check.  Also add the proper task into the conflict tasks list.  Previously the "continue with" tasks was being added, but the actual work task was being removed, which means the list would grow forever (full of completed tasks).
=> CBL-4289: Don't skip waiting for pending conflict tasks

src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs
Also rework a test to check for null documents since one of the changes in LiteCore slightly changes a behavior so that instead of corrupted document content, the document is null.  Without this test change the test failure is confusing because it is a null reference exception.
=> Bump LiteCore to 3.1.0-350

src/Couchbase.Lite.Shared/API/Query/Function.cs
A null value will be interpreted as `Expression.All()`
=> CBL-3386: Allow null in `Function.Count(IExpression)`

src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs, src/Couchbase.Lite.Tests.Shared/TLSIdentityTest.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
Actual code fixes in EE repo.  The status is that dynamically generated X509 certificates will never function until .NET 8.  Static certificates not trusted by default will need a network security config entry.  Intermediate certificate pinning is also not going to work, and no fix for that seems to be scheduled yet.
Ref: https://github.com/dotnet/runtime/issues/84202 and https://github.com/dotnet/runtime/issues/45741
=> Tweak which tests get run on .NET 6 Android

src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
The old implementation mistakenly believed that calling `Freeze()` was enough, but that method returns a frozen copy, and doesn't modify in place.
=> CBL-4421: Properly freeze collection configuration after used in Replicator

src/Couchbase.Lite.Shared/Query/DatabaseSource.cs, src/Couchbase.Lite.Shared/Query/From.cs, src/Couchbase.Lite.Shared/Query/QueryBase.cs, src/Couchbase.Lite.Shared/Query/QueryResultSet.cs, src/Couchbase.Lite.Shared/Query/XQuery.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs
The heart of the problem was the methods to add and remove active stoppables in QueryBase.  In the case of DataSource.Collection, the Database property will be null and so this logic was silently skipped.
=> CBL-4419: Live queries built using DataSource.Collection don't get added to Database Stoppable list

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
GetDefaultCollection will now return a new object if it detects that the previously stored one has been invalidated by a dispose
=> CBL-4426: Correct an error with disposing the default collection

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs
GetDefaultCollection will now return a new object if it detects that the previously stored one has been invalidated by a dispose
This is ported from 0b179984e03cb43be5af6efa50af8ca7745443e7 via cherry pick plus extra changes (removing a redundant variable and its usage.  The change was too large for the release branch)
=> CBL-4427: Correct an error with disposing the default collection

src/Couchbase.Lite.Shared/Support/iOS/IOSProxy.cs
Without this, the AOT compiler will not realize them and they will fail at runtime
=> CBL-4505: Add attributes to iOS proxy unmanaged delegates

packaging/nuget/do_package.ps1, src/Couchbase.Lite/Couchbase.Lite.csproj
Many others have native pdb which confuse nuget.org and cause the package to be rejected.  In the same spirit, change all Couchbase.Lite pdb to be portable.
=> CBL-4480: Only make snupkg for the main nuget package

Jenkinsfile, packaging/nuget/do_package.ps1, src/Couchbase.Lite/Couchbase.Lite.csproj
Many others have native pdb which confuse nuget.org and cause the package to be rejected.  In the same spirit, change all Couchbase.Lite pdb to be portable.
=> CBL-4481: Only make snupkg for the main nuget package

src/Couchbase.Lite.Shared/Query/NQuery.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs, src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs
The changes needed are in NQuery.cs and a test was updated to include this in QueryTest.cs.  The other two changes are needed because otherwise .NET 4.6.2 fails to build correctly.
=> CBL-4528: Correctly pass parameters for SQL++ query

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
This basically makes disposal a tri-state process:
1. If dispose is called, then set the state to disposing 2a. If the replicator is stopped, set the state to disposed and perform cleanup 2b. If the replicator is not stopped, call stop and wait for the stopped callback
3. If stopped is called and the state is disposing, perform the cleanup and set the state to disposed
=> CBL-4433: Defer replicator cleanup until stop

packaging/nuget/couchbase-lite.nuspec, src/Couchbase.Lite/Couchbase.Lite.csproj
System.Collections.Immutable is available without a package on many platforms Microsoft.Bcl.AsyncInterfaces is completely unused Microsoft.Win32.Registry is available everywhere that it is needed, without a package
=> CBL-4516 CBL-4527: Remove unneeded deps from project and nuspec

src/Couchbase.Lite.Shared/Support/iOS/IOSProxy.cs
Without this, the AOT compiler will not realize them and they will fail at runtime
=> CBL-4504: Add attributes to iOS proxy unmanaged delegates

src/Couchbase.Lite.Shared/API/DI/IReachability.cs, src/Couchbase.Lite.Shared/API/DI/Service.cs, src/Couchbase.Lite.Shared/Sync/Reachability.cs
This won't have any bearing on most users, but in rare cases they may want to provide their own reachability logic in guided support cases
=>  CBL-4550: Make IReachability public

src/Couchbase.Lite.Shared/API/DI/IReachability.cs, src/Couchbase.Lite.Shared/API/DI/Service.cs, src/Couchbase.Lite.Shared/Sync/Reachability.cs
This won't have any bearing on most users, but in rare cases they may want to provide their own reachability logic in guided support cases
=> CBL-4578: Make IReachability public

src/Couchbase.Lite.Shared/API/DI/IReachability.cs, src/Couchbase.Lite.Shared/API/DI/Service.cs, src/Couchbase.Lite.Shared/Sync/Reachability.cs
This won't have any bearing on most users, but in rare cases they may want to provide their own reachability logic in guided support cases
=> CBL-4577: Make IReachability public

src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems, src/Couchbase.Lite.Tests.Shared/CouchbaseTestFramework.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/Couchbase.Lite.Tests.Shared/xunit.runner.json
To try to get more information during test runs about tests that are long running, etc.  Prepare for more functionality at a later date.
=> Add in custom xunit test framework and config

packaging/nuget/couchbase-lite-support-android.nuspec, packaging/nuget/couchbase-lite-support-ios.nuspec, packaging/nuget/couchbase-lite.nuspec, src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj, src/Couchbase.Lite.Support.Apple/iOS/Couchbase.Lite.Support.iOS.csproj, src/Couchbase.Lite.Tests.Shared/BlobTest.cs, src/Couchbase.Lite.Tests.Shared/PerfTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/TLSIdentityTest.cs, src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/Couchbase.Lite/Couchbase.Lite.csproj
Since .NET has a different Microsoft support lifecycle for these targets (.NET 6 already out of support)
=> CBL-4613: Upgrade .NET non-windows to .NET 7

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs
This will prevent situations in which the native object is recreated, and then never disposed because dispose was already called
=> CBL-4652: Don't allow calls to API after object disposed

src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs
It is meaningless and doesn't translate well into BLIP.  Sync Gateway will reject it with an HTTP 400.  To be tested with the developer pytest suite.
=> CBL-4744: Don't allow zero length lists for channels or docIDs

src/build/do_fetch_litecore.ps1
It causes an incorrect python invocation
=> Fix a small error in the fetch LiteCore script

src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/LiteCore/test/LiteCore.Tests.Shared/TestBase.cs
The multiple replicators test had some flaky logic in it that sometimes caused that particular test to hang and endless print PING PONG every 5 minutes.  Backported https://github.com/couchbase/couchbase-lite-net/commit/8efacff992e134d4039c4082259e33c10bd4148d to thie branch.  The tests still hung after that, however, so I added in some logging for when a test begins.  This alone caused the hang to stop (or maybe it just didn't feel like hanging today) but it's a good change to keep just in case the hangs come back.
=> CBL-4891: Backport a hanging test fix and log test starts

src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
* CBL-4980 : Added the missing document subscript in Collection class
* CBL-4953 : Deprecated document subscript in Database class
* Document Subscript Operator is .NET and iOS specific operator for getting a document frament object by id from a collection such as 
```
var doc = collection["doc1"];
var name = doc["name"].String;
```
=> Add doc subscript in Collection and Deprecate the Database's one

core_version.ini, src/Couchbase.Lite.Shared/API/Database/Scope.cs
* Updated LiteCore to 3.2.0-103.
* Allowed NotFound error when getting a collection as LiteCore now returns NotFound error when the collection doesn't exist.
=> Update LiteCore to 3.2.0-103

src/Couchbase.Lite.Shared/Log/LogTo.cs
This the same issue, backported to helium
=> CBL-4983: Map LiteCore log domain 'Changes' to Database instead of Replicator

src/Couchbase.Lite.Tests.iOS/Couchbase.Lite.Tests.iOS.csproj
I had a reminder to do this in the EE package rework PR but it didn't save the CE one so this is the correction.  Without these definitions none of the EE API tests will run.
=> Add in the COUCHBASE_ENTERPRISE defs that were temporarily removed

src/Couchbase.Lite.Support.NetDesktop/Activate.cs, src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj, src/Couchbase.Lite.Support.NetDesktop/desktop.props, src/Couchbase.Lite.Support.UWP/Couchbase.Lite.Support.UWP.csproj, src/Couchbase.Lite.Support.WinUI/Couchbase.Lite.Support.WinUI.csproj
Basically, when putting LiteCore into nuget put it into a folder named win-<arch> instead of win10-<arch>.  The reason I put it in win10-<arch> in the first place was to sort of have a few more hints that we weren't supporting Windows 7 or 8.  Nobody seems to be under that misconception anyway, now, and the toolchain is actually complaining about this so I will oblige.  It doesn't hurt the code any, as long as everything agrees on the location.
This will be kind of weird to test because PR validation is meaningless.  The post commit tests which run tests on the packaged library will show pretty quickly if anything is wrong.
=> CBL-5304: Remove version specific Windows RID from nuget package

src/Couchbase.Lite.Shared/Sync/HTTPLogic.cs
Before it was strictly three, which made 3.1.3.1 appear as 1.3.1 (for example).
=> CBL-5006: Parse any number of version digits

src/Couchbase.Lite.Shared/Support/iOS/iOSConsoleLogger.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs
.NET has yet to do this in the Console class and it is unclear if they can or will
=> CBL-5397: Replace NSLog with os_log

src/Couchbase.Lite.Shared/Serialization/MDict.cs
The termination condition is when key is null, not when next returns false
=> CBL-5356: Fix incorrect FLDictIterator loop

src/Couchbase.Lite.Shared/API/Document/ArrayObject.cs, src/Couchbase.Lite.Shared/API/Document/MutableArrayObject.cs, src/Couchbase.Lite.Shared/API/Query/IResultSet.cs, src/Couchbase.Lite.Shared/API/Query/Result.cs, src/Couchbase.Lite.Shared/Query/NQuery.cs, src/Couchbase.Lite.Shared/Query/QueryBase.cs, src/Couchbase.Lite.Shared/Query/QueryResultSet.cs, src/Couchbase.Lite.Shared/Query/XQuery.cs, src/Couchbase.Lite.Shared/Serialization/FleeceMutableArray.cs, src/Couchbase.Lite.Shared/Serialization/MContext.cs, src/Couchbase.Lite.Shared/Serialization/MDict.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs
If the query is disposed, and then any of its results are used (in particular ones that involve collections are especially affected) then garbage native data will be used.  Try to catch this using Dispose and refuse to go further with it.
=> Fix a use after dispose issue in query result objects

src/AssemblyInfo.props, src/Couchbase.Lite.Shared/API/Query/Expression.cs, src/Couchbase.Lite.Shared/API/Query/IIndex.cs, src/Couchbase.Lite.Shared/Util/CBDebug.cs
See #1607 for the discovery process, but these nullability annotations are incorrect, and there is a new behavior in .NET causing problems with the version string.
=> CBL-5547: Nullability regressions

src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Tests.Shared/DocumentTest.cs
Transactions disallow this anyway with a weirder message, so stop it before it happens.  You can no longer attempt to use the same collection from two different database instances when reading and writing a document.
=> CBL-5517: Disallow save using collection from differing DB instance

src/Couchbase.Lite.Shared/API/Document/Document.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/Couchbase.Lite.Tests.Shared/TLSIdentityTest.cs
Collection equality is more strict now so a few places that rely on equals need a different mechanism for comparison TLSIdentity.CreateIdentity does not allow null anymore via nullability instead of just checking at runtime so the exception changed away from empty cert attribute for null to just argument null exception (via compiler) Document equality needs to be relaxed back to the way it was whereby documents are equal if their contents are equal and they come from the same underlying database
=> Fix a few tests that are no longer valid

src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj, src/Couchbase.Lite.Support.Android/android.props
It needs a special file to tell it to deploy LiteCore along with the application being built.
=> While .NET 6 and above automatically uses native libs, Xamarin does not

src/Couchbase.Lite.Tests.Shared/QueryTest.cs
Math.PI has 17 total digits but double can only guarantee 15, so round to 14 fractional for 15 total.  This test was failing because equality comparison was failing due to the high precision on iOS and Android
=> Fix too high precision in TestQueryExpressions

packaging/nuget/couchbase-lite-support-netdesktop.nuspec, packaging/nuget/couchbase-lite-support-uwp.nuspec, packaging/nuget/couchbase-lite-support-winui.nuspec, src/Couchbase.Lite.Support.NetDesktop/Activate.cs, src/Couchbase.Lite.Support.NetDesktop/desktop.targets
This mechanism is deprecated by Microsoft.  This change is manually ported from d000308b3510bc356b88723e467c6c8b3f6667ea because in 3.2 the packaging files are different (csproj vs nuspec).
=> CBL-3505: Remove version specific RID from packaging

src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
There is no reliable mechanism for capturing the max active count of multiple replicators from the passive side.  There are no listeners so the only choice is polling and sometimes polling can poll at the wrong time and give bad results.  Have to give up on this part of the test.
=> CBL-5000: Modify multiple replicator test to be less flaky

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/Query/QueryIndex.cs
.NET was already doing most of this, aside from an o for representing "one-shot"
Along for the ride in this commit is a nullability regression fix
=> CBL-5566: Replicator ID markings in logs

src/Couchbase.Lite.Shared/Query/QueryBase.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs
Accessing ColumnNames after dispose will cause a native null deference without this fix.
=> CBL-5727: Throw exception instead of native crash with ColumnNames

src/Couchbase.Lite.Shared/Query/QueryIndex.cs
It needs to stay null otherwise the stemming might have unexpected results if the default happens to be "en".
=> CBL-5747: Don't use default value for Index null locale

Jenkinsfile, src/Couchbase.Lite.Tests.Android/Couchbase.Lite.Tests.Android.csproj, src/Couchbase.Lite.Tests.NetCore/Couchbase.Lite.Tests.NetCore.csproj, src/Couchbase.Lite.Tests.Shared/DatabaseEncryptionTest.cs, src/Couchbase.Lite.Tests.Shared/TLSIdentityTest.cs, src/Couchbase.Lite.Tests.iOS/Couchbase.Lite.Tests.iOS.csproj
- DatabaseEncryptionTests were creating EncryptionKeys too rapidly and causing out of memory issues (cache EncryptionKeys between tests to solve this)
- ImportIdentity doesn't function on API 22 for reasons that appear to be an Android bug (skip the failing test on API 22 and below)
=> CBL-5782: Fix two points that were causing .NET Android testing issues

src/Couchbase.Lite.Tests.Android/Couchbase.Lite.Tests.Android.csproj, src/Couchbase.Lite.Tests.NetCore/Couchbase.Lite.Tests.NetCore.csproj, src/Couchbase.Lite.Tests.Shared/CSharpTest.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/Couchbase.Lite.Tests.Shared/DocumentTest.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs, src/Couchbase.Lite.Tests.Shared/NotificationTest.cs, src/Couchbase.Lite.Tests.Shared/P2PTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.QueryTest.cs, src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/Couchbase.Lite.Tests.iOS/Couchbase.Lite.Tests.iOS.csproj
The tests to exclude are only about 40, but those 40 account for about half of the test runtime (usually due to artificial thread sleeping and such).
Tier 2 platforms are largely judged by their re-use of an identical LiteCore on another platform:
Xamarin Android -> Same as .NET Android
Xamarin iOS -> Same as .NET iOS
.NET Mac Catalyst -> Same as .NET iOS
.NET WinUI -> Same as .NET 6
.NET Framework -> Same as .NET 6
=> CBL-5781: Create a sanity suite of tests to run on tier 2 platforms

src/LiteCore/src/LiteCore.Shared/Interop/NativeHandler.cs
If they return false with an error code of 0, the platform interprets that (incorrectly) as true
=> Fix an apparently longstanding issue with core boolean methods

src/Couchbase.Lite.Shared/API/Database/Collection.cs
It's not an error condition, so null should be returned.
=> Allow missing index error to be handled in GetIndex

src/Couchbase.Lite.Shared/API/Database/Collection.cs
Not quite a cherry pick of 7184cc8272631a04d3a998ddb294a2ae2c1d3a44 , but it is a literal copy paste from the newer source into the correct places.
=> CBL-5790: Fix issue where exception in save causes memory leak

core_version.ini, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Database/DatabaseConfiguration.cs, src/Couchbase.Lite.Shared/API/Info/Defaults.cs, src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems, src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4DatabaseTypes_defs.cs
This differs moderately from the 3.1 counterpart in the following ways for the tests (the actual logic, while not cherry picked, is identical via copy/paste):
1. 3.2 and newer don't expose c4db_getConfig2 directly from the library, but the same technique can be used in the test itself to resolve the native symbol (see TestNative in the new test file)
2. Theory is used instead of local function now that UWP is gone (it used a different underlying testing framework that didn't understand Theory)
=> CBL-6073: Implement FullSync feature (and update Core to 3.2.0-223)

src/Couchbase.Lite.Shared/Query/NQuery.cs
That means that the build fails on the project when using things like `?` and `!`
=> Forgot that 3.1 doesn't have nullability available

Jenkinsfile, core_version.ini, src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Shared/Query/NQuery.cs, src/Couchbase.Lite.Shared/Query/QueryBase.cs, src/Couchbase.Lite.Shared/Query/XQuery.cs, src/Couchbase.Lite.Tests.Shared/CSharpTest.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.QueryTest.cs, src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/LiteCore/src/LiteCore.Shared/API/NativeWrapper.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Collection_native_safe.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Socket_native_safe.cs
There are a lot of things going on here but this gives me a green test run:
1. Incorrect logic for firing document changed listener
2. Revert to NQuery and XQuery that create the internal C4Query in a void method, rather than returning
3. Database test for query listener has redundant logic that seems to prove nothing
4. Migrate two tests that were testing two modes each into one test each with two variants to be more clear about which one failed
5. Fix a test issue comparing collections from different databases since that was changed to not be allowed
6. Change ports on TestBusyPort so that it doesn't fail when I happen to have Sync Gateway running (which uses the same port)
7. Fix awful error where nativewrapper will never free any native objects because it's ref count starts at 0 …
=> Fix up issues that probably came in during a rebase

src/Couchbase.Lite.Shared/API/DI/Service.cs, src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj, src/Couchbase.Lite.Tests.Shared/CSharpTest.cs, src/Couchbase.Lite.Tests.Shared/CouchbaseTestFramework.cs, src/Couchbase.Lite.Tests.Shared/LoadTest.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs, src/Couchbase.Lite.Tests.Shared/PerfTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/TunesPerfTest.cs, src/Couchbase.Lite.Tests.Shared/Util/Benchmark.cs, src/Couchbase.Lite.Tests.Shared/Util/Try.cs, src/Couchbase.Lite.Tests.Shared/Util/XunitLogger.cs, src/Couchbase.Lite.Tests.Shared/WebSocketTest.cs, src/Couchbase.Lite/Couchbase.Lite.csproj, src/LiteCore/src/LiteCore.Shared/Interop/NativeActivate.cs
Remove defunct WINDOWS_UWP and NETSTANDARD2_0
Bump to net8.0 console since net6.0 support is ending in Nov 2024
=> Cleanup defines in the project

src/Couchbase.Lite.Tests.Shared/CSharpTest.cs, src/LiteCore/src/LiteCore.Shared/API/NativeWrapper.cs
Since at this point the object is about to be collected, which means nothing is referencing it and something forgot to call "Dispose".
Also, put in some workarounds for flakiness in Jenkins tests
=> CBL-6254: NativeWrapper finalizer should not consider refCount

src/Couchbase.Lite.Support.NetDesktop/Activate.cs
Self contained .NET applications will collapse into a single architecture, and will copy everything needed to the output directory automatically.  This means LiteCore.dll will be next to the executable and not in any subdirectory as it was in .net framework.
=> CBL-6236: Include the exe directory in the LiteCore search path

src/Couchbase.Lite.Support.NetDesktop/Activate.cs
Self contained .NET applications will collapse into a single architecture, and will copy everything needed to the output directory automatically.  This means LiteCore.dll will be next to the executable and not in any subdirectory as it was in .net framework.
=> CBL-6236: Include the exe directory in the LiteCore search path (#1665)

core_version.ini, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Database/DatabaseConfiguration.cs, src/Couchbase.Lite.Shared/API/Info/Defaults.cs, src/Couchbase.Lite.Tests.Shared/ArrayIndexTest.cs, src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems, src/Couchbase.Lite.Tests.Shared/MmapTest.cs, src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs, src/Couchbase.Lite.Tests.Shared/Util/ImplementsTestSpecAttribute.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4DatabaseTypes_defs.cs, src/LiteCore/src/LiteCore.Shared/Interop/FLBase_defs.cs, src/LiteCore/src/LiteCore.Shared/Interop/FLSlice_defs.cs, src/LiteCore/src/LiteCore.Shared/Interop/Fleece.cs
Also sneaking in a few other small things here:
- Support for tool based test spec verification (ImplementsTestSpecAttribute)
- Complete ArrayIndexTest now that c4index_getOptions returns unnestPath
- Update LiteCore to 3.2.1-8
=> CBL-6308: Implement MmapEnabled property on DatabaseConfiguration

core_version.ini, src/Couchbase.Lite.Shared/API/Document/Document+private.cs, src/Couchbase.Lite.Shared/API/Document/Document.cs, src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems, src/LiteCore/binding_list/c4.def, src/LiteCore/parse/config_c4.py, src/LiteCore/src/LiteCore.Shared/Interop/C4Document.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Document_native.cs, src/LiteCore/src/LiteCore.Shared/Interop/Fleece.cs
This is just for parity so the testing server can build against both 3.2 and 4.0
=> CBL-6348:  Implement RevisionIDs API (unsupported, for testing only)

src/Couchbase.Lite.Shared/Query/XQuery.cs, src/Couchbase.Lite.Tests.Shared/ConcurrencyTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4DatabaseTypes_defs.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4IndexTypes_defs.cs
Forgot to do this when upgrading LiteCore itself and it only manifest itself in some tests that are only run in release mode.
Nullability fix (Check() guarantees _c4Query is either null or an exception is thrown)
Fix a test for the new thread safety model (c4query_run is not blocked, just c4queryenum functionality on the query)
=> Update the structs for LiteCore interop

src/Couchbase.Lite.Shared/API/Database/DatabaseConfiguration.cs, src/Couchbase.Lite.Shared/Support/WinUI/DefaultDirectoryResolver.cs
Also evaluate it lazily to save some overhead
Cherry picked cleanly from 97bdb27112a0727248ac0f3d12cdfeb3876eecbb
=> CBL-6482: Create two variants (packaged / unpackaged) of defaultdirectoryresolver

src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs
The replicator automatically stop when going in the background and the value of the property is false (the default).  Currently, it is reversed and only automatically stops when the property is true.
=> CBL-6540: AllowReplicatingInBackground behavior is opposite of what is documented

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Log/Log.cs
Without doing this, accessing Database.Log throws a null reference exception (or some other nonsense).
Fix some incorrect comments as well.  Note that trying to do the log initialization using atomic swaps causes a hang, and I don't think it's enough of an issue to figure out why so just do a noobie swap.
=> Fix a bizarre native AOT problem with iOS

src/Couchbase.Lite.Shared/API/Log/FileLogger.cs, src/Couchbase.Lite.Shared/Log/Log.cs, src/LiteCore/src/LiteCore.Shared/Interop/Misc_native.cs
Now that the C API copies the domain name on input, it is no longer important for the C# side string to live pinned past the method invocation.
=> CBL-6798: Don't allocate memory for c4log_getDomain

src/Couchbase.Lite.Support.NetDesktop/Activate.cs
There was an accidental breaking change by Microsoft since then, so earlier versions cause LiteCore crashing.
=> Update required C++ runtime to 14.40

src/Couchbase.Lite.Tests.Shared/Util/WaitAssert.cs
Otherwise .NET 4.6.2 tests cannot pass on Jenkins due to an error about waitall not being supported on STA threads.
=> Port WaitAssert fix from 3.2

src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Tests.NetCore/Couchbase.Lite.Tests.NetCore.csproj, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/Couchbase.Lite.Tests.Shared/DocPerfTest.cs, src/Couchbase.Lite.Tests.Shared/MmapTest.cs, src/Couchbase.Lite.Tests.Shared/NotificationTest.cs, src/Couchbase.Lite.Tests.Shared/P2PTest.cs, src/Couchbase.Lite.Tests.Shared/PerfTest.cs, src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs, src/Couchbase.Lite.Tests.Shared/QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.QueryTest.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/TLSIdentityTest.cs, src/Couchbase.Lite.Tests.Shared/TestCase.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/Couchbase.Lite.Tests.Shared/Util/Try.cs, src/Couchbase.Lite.Tests.Shared/Util/WaitAssert.cs, src/Couchbase.Lite.Tests.Shared/VersionVectorTests.cs, src/Couchbase.Lite.Tests.Shared/WebSocketTest.cs
On the way I was able to fix a few things:
- Get rid of all WaitHandle.WaitAll calls so that the .NET 4.6.2 tests stop failing because xUnit runs on STAThread threads.
- Turn off version vectors since this is 3.3.0 now
=> CBL-7052: Completely remove FluentAssertions from testing

src/Couchbase.Lite.Shared/API/Database/Collection.cs, src/Couchbase.Lite.Shared/API/Database/Database.cs, src/Couchbase.Lite.Shared/API/Database/DatabaseConfiguration.cs, src/Couchbase.Lite.Shared/API/Database/Scope.cs, src/Couchbase.Lite.Shared/API/Info/Defaults.cs, src/Couchbase.Lite.Shared/API/Log/FileLogger.cs, src/Couchbase.Lite.Shared/API/Query/ArrayIndexConfiguration.cs, src/Couchbase.Lite.Shared/API/Query/FullTextIndexConfiguration.cs, src/Couchbase.Lite.Shared/API/Query/ValueIndexConfiguration.cs, src/Couchbase.Lite.Shared/API/Sync/BasicAuthenticator.cs, src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs, src/Couchbase.Lite.Shared/API/Sync/Replicator.cs, src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs, src/Couchbase.Lite.Shared/Query/IndexConfiguration.cs, src/Couchbase.Lite.Tests.Shared/CSharpTest.cs, src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs, src/Couchbase.Lite.Tests.Shared/DictionaryTest.cs, src/Couchbase.Lite.Tests.Shared/LogTest.cs, src/Couchbase.Lite.Tests.Shared/MmapTest.cs, src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs, src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs, src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs, src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs, src/Couchbase.Lite.Tests.Shared/VersionVectorTests.cs, src/LiteCore/src/LiteCore.Shared/API/NativeWrapper.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native_safe.cs
CBL-1946 CBL-3813
Migrate configuration objects to be init only (much less checking required to ensure it is not changed while in use) Fix a few potential null deferences based on static analysis Undeprecate the BasicAuthenticator string constructor since there are no plans to ever remove it Fix tests to use init only style
Fix an unused variable in C4ReplicatorWrapper
=> API breaking changes for 4.0

src/Couchbase.Lite.Shared/API/Query/FullTextIndexConfiguration.cs, src/Couchbase.Lite.Shared/API/Query/ValueIndexConfiguration.cs, src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems, src/Couchbase.Lite.Tests.Shared/PartialIndexTest.cs
=> CBL-7256: Partial Index API and tests

src/Couchbase.Lite.Tests.Shared/ConcurrencyTest.cs, src/LiteCore/src/LiteCore.Shared/Interop/C4Database_native_safe.cs
Two of them weren't updated to catch the new exception type for closed DB One was a bigger problem of not locking out other API calls during a db transaction on the same db object
=> Fix some failing release build test
