couchbase/couchbase-lite-net

- src/Couchbase.Lite.Shared/Util/CookieStore.cs
> Add CookieStore hack for MSFT .NET.

- src/Couchbase.Lite.Shared/Manager.cs
- src/Couchbase.Lite.Shared/Manager/SharedState.cs
- src/Couchbase.Lite.Shared/Query.cs
- src/Couchbase.Lite.Shared/Query/LiveQuery.cs
- src/Couchbase.Lite.Shared/View.cs
- src/Couchbase.Lite.Tests.Shared/ViewsTest.cs
> Fixes Issue #383

- samples/CouchbaseSample.iOS/CouchtableDelegate.cs
- samples/CouchbaseSample.iOS/RootViewController.cs
- samples/SimpleAndroidSync/List.cs
- samples/SimpleAndroidSync/MainActivity.cs
- Unified keys between iOS and Android samples
- Added date property to Android
> Fixed replication between CouchbaseSample.iOS and SimpleAndroidSync

- samples/SimpleAndroidSync/List.cs
- samples/SimpleAndroidSync/LiveQueryAdapter.cs
- samples/SimpleAndroidSync/MainActivity.cs
Adds delete support for SimpleAndroidSync
> Add delete android sync

- samples/CouchbaseSample.iOS/RootViewController.cs
- samples/SimpleAndroidSync/List.cs
- samples/SimpleAndroidSync/MainActivity.cs
Use the same "check" key to allow syncing with https://github.com/couchbaselabs/GrocerySync-Android
> Allow syncing with native grocery sync apps

- src/Couchbase.Lite.Shared/Auth/PersonaAuthorizer.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Database.cs
- src/Couchbase.Lite.Shared/Replication.cs
- src/Couchbase.Lite.Shared/Replication/Pusher.cs
- src/Couchbase.Lite.Shared/Replication/ReplicationOptions.cs
- src/Couchbase.Lite.Shared/Util/ExtensionMethods.cs
- src/Couchbase.Lite.Shared/Util/JsonUtility.cs
- src/Couchbase.Lite.Shared/Util/Log.cs
- src/Couchbase.Lite.Shared/Util/LogTo.cs
- src/Couchbase.Lite.Shared/Util/Misc.cs
- src/Couchbase.Lite.Shared/Util/TimeSeries.cs
- src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/TimeSeriesTest.cs
- src/Couchbase.Lite.Tests.Shared/Util/RemoteLogger.cs
- src/StorageEngines/ForestDB/storage.forestdb.net45/storage.forestdb.net45.csproj
> Implement remote logging

- src/Couchbase.Lite.Android.sln
- src/Couchbase.Lite.iOS.sln
- src/ListenerComponent/ListenerConsole/LiteServ.sln
- src/ListenerComponent/LiteServ.Android/Assets/AboutAssets.txt
- src/ListenerComponent/LiteServ.Android/LiteServ.Android.csproj
- src/ListenerComponent/LiteServ.Android/LiteServ.Android.sln
- src/ListenerComponent/LiteServ.Android/MainActivity.cs
- src/ListenerComponent/LiteServ.Android/Properties/AndroidManifest.xml
- src/ListenerComponent/LiteServ.Android/Properties/AssemblyInfo.cs
- src/ListenerComponent/LiteServ.Android/Resources/AboutResources.txt
- src/ListenerComponent/LiteServ.Android/Resources/values/Strings.xml
- src/ListenerComponent/LiteServ.Android/app.config
- src/ListenerComponent/LiteServ.Android/packages.config
- src/ListenerComponent/LiteServ.Shared/ListenerShared.cs
- src/ListenerComponent/LiteServ.Shared/LiteServ.Shared.projitems
- src/ListenerComponent/LiteServ.Shared/LiteServ.Shared.shproj
- src/ListenerComponent/LiteServ.iOS/AppDelegate.cs
- src/ListenerComponent/LiteServ.iOS/Assets.xcassets/AppIcons.appiconset/Contents.json
- src/ListenerComponent/LiteServ.iOS/Assets.xcassets/Contents.json
- src/ListenerComponent/LiteServ.iOS/Entitlements.plist
- src/ListenerComponent/LiteServ.iOS/Info.plist
- src/ListenerComponent/LiteServ.iOS/LaunchScreen.storyboard
- src/ListenerComponent/LiteServ.iOS/LiteServ.iOS.csproj
- src/ListenerComponent/LiteServ.iOS/LiteServ.iOS.sln
- src/ListenerComponent/LiteServ.iOS/Main.cs
- src/ListenerComponent/LiteServ.iOS/Main.storyboard
- src/ListenerComponent/LiteServ.iOS/ViewController.cs
- src/ListenerComponent/LiteServ.iOS/packages.config
Created simple iOS and Android apps that implement LiteServ. There are some merge conflicts with a few solution files.
> Implemented LiteServ on Android and iOS platforms

- src/Couchbase.Lite.Shared/Auth/RemoteLogin.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Replication/ChangeTracker.cs
- src/Couchbase.Lite.Shared/Replication/ExceptionResolver.cs
- src/Couchbase.Lite.Shared/Replication/IChangeTrackerClient.cs
- src/Couchbase.Lite.Shared/Replication/Puller.cs
- src/Couchbase.Lite.Shared/Replication/SocketChangeTracker.cs
- src/Couchbase.Lite.Shared/Replication/WebSocketChangeTracker.cs
- src/Couchbase.Lite.Shared/Util/Misc.cs
- src/Couchbase.Lite.Shared/Util/TransientErrorRetryHandler.cs
- src/Couchbase.Lite.Tests.Shared/ChangeTrackerTest.cs
- src/Couchbase.Lite.Tests.Shared/MiscTest.cs
Fixes #718
Fixes #728
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/743)
> Refactor retry logic for replication

- src/Couchbase.Lite.Tests.Shared/RouterTests.cs
- src/ListenerComponent/Couchbase.Lite.Listener.Shared/PeerToPeer/CouchbaseListenerContext.cs
Fixes #745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/747)
> Fixes #745

- src/Couchbase.Lite.Android/Couchbase.Lite.Android.csproj
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Replication/Batcher.cs
- src/Couchbase.Lite.Shared/Replication/CouchbaseLiteHttpClientFactory.cs
- src/Couchbase.Lite.Shared/Replication/ReplicationOptions.cs
- src/Couchbase.Lite.Shared/Util/UniqueQueue.cs
Closes #742 by eliminating a performance regression with batcher deduplication
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/761)
> Close Issue #742

- src/Couchbase.Lite.Shared/Replication.cs
Fixes #757
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/769)
> Fixes #757

- src/Couchbase.Lite.Shared/Replication/Pusher.cs
- src/Couchbase.Lite.Tests.Shared/AttachmentsTest.cs
Fixes #766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/770)
> Fixes #766

- src/Couchbase.Lite.Shared/Replication/Puller.cs
Fixes #755
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/771)
> Fixes #755

- src/Couchbase.Lite.Shared/Replication/MultipartDocumentReader.cs
Fixes #779
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/781)
> Fixes #779

- src/Couchbase.Lite.Shared/Replication/Pusher.cs
- src/Couchbase.Lite.Tests.Shared/Assets/GatewayConfig.json
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
Fixes #756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/791)
> Fixes #756

- src/Couchbase.Lite.Shared/Manager/IJsonSerializer.cs
- src/Couchbase.Lite.Shared/Manager/INetworkReachabilityManager.cs
- src/Couchbase.Lite.Shared/Manager/NetworkReachabilityManager.cs
- src/Couchbase.Lite.Shared/Manager/NewtonsoftJsonSerializer.cs
- src/Couchbase.Lite.Shared/Replication.cs
- src/Couchbase.Lite.Shared/Replication/BulkDownloader.cs
- src/Couchbase.Lite.Shared/Replication/CouchbaseLiteHttpClient.cs
- src/Couchbase.Lite.Shared/Replication/CouchbaseLiteHttpClientFactory.cs
- src/Couchbase.Lite.Shared/Replication/IChangeTrackerClient.cs
- src/Couchbase.Lite.Shared/Replication/OneShotOrLongPollLogic.cs
- src/Couchbase.Lite.Shared/Replication/Puller.cs
- src/Couchbase.Lite.Shared/Replication/Pusher.cs
- src/Couchbase.Lite.Shared/Replication/RemoteSession.cs
- src/Couchbase.Lite.Shared/Replication/SocketChangeTracker.cs
- src/Couchbase.Lite.Shared/Replication/WebSocketChangeTracker.cs
- src/Couchbase.Lite.Shared/Util/IHttpClientFactory.cs
- src/Couchbase.Lite.Shared/Util/Leasable.cs
- src/Couchbase.Lite.Tests.Shared/ChangeTrackerTest.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/798)
> Fixes #776 and #796

- OSLicenses/SharpZipLib.txt
Jim,
This is to add the SharpZipLib license to the repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/861)
> For licensing

- docs/examples/api-walkthrough/api-walkthrough/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/883)
> live query and replication change listener examples.

- docs/examples/api-walkthrough/api-walkthrough/ExampleConflictResolver.cs
- docs/examples/api-walkthrough/api-walkthrough/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/896)
> conflict resolver example.

- src/Couchbase.Lite.Shared/Database/ICouchStore.cs
- src/Couchbase.Lite.Shared/Replication/BulkDownloader.cs
- src/Couchbase.Lite.Shared/Replication/Puller.cs
- src/ListenerComponent/Couchbase.Lite.Listener.Shared/PeerToPeer/DatabaseMethods.cs
- src/StorageEngines/ForestDB/storage.forestdb.shared/src/ForestDBCouchStore.cs
- src/StorageEngines/SQLiteCommon/storage.sqlite.common/src/SqliteCouchStore.cs
Fixes #910 (Channel removal potentially disrupts attachments)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/911)
> Fixes #910

- docs/examples/api-walkthrough/api-walkthrough/Program.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/998)
> wildcard character match tag

- docs/examples/api-walkthrough/api-walkthrough/Program.cs
- docs/modules/ROOT/pages/csharp.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/1015)
> [docs] getting started and upgrade

- docs/examples/api-walkthrough/api-walkthrough/Program.cs
- docs/modules/ROOT/pages/csharp.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/1022)
> [docs] 2.0 updates

- docs/antora.yml
- docs/examples/api-walkthrough/api-walkthrough/Program.cs
- docs/examples/api-walkthrough/api-walkthrough/api-walkthrough.csproj
- docs/modules/ROOT/pages/_partials/pre-release-instructions.adoc
- docs/modules/ROOT/pages/_partials/release-instructions.adoc
- docs/modules/ROOT/pages/csharp.adoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/1021)
> [docs] 2.1 DB1

- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
Add a test case to test when server is closed when replicator point to none existed uri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/1030)
> #1020 Test to close server when replicator point to none existed uri

- appveyor.yml
- src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj
- src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj
- src/Couchbase.Lite.Support.UWP/Couchbase.Lite.Support.UWP.csproj
- src/Couchbase.Lite.Tests.UWP/Couchbase.Lite.Tests.UWP.sln
Trying to get some sanity CI going for PR / master
> More corrections to appveyor.yml

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
Adding push filter and pull validator
> push filter & pull validator

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Document/Blob.cs
- src/Couchbase.Lite.Shared/API/Query/Expression.cs
- src/Couchbase.Lite.Shared/API/Query/Function.cs
- src/Couchbase.Lite.Shared/API/Query/Parameters.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Query/QueryCollectionExpression.cs
- src/Couchbase.Lite.Shared/Query/QueryCompoundExpression.cs
- src/Couchbase.Lite.Shared/Query/XQuery.cs
- src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj
- src/Couchbase.Lite.Support.Apple/iOS/Couchbase.Lite.Support.iOS.csproj
- src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj
- src/Couchbase.Lite.Support.UWP/Couchbase.Lite.Support.UWP.csproj
- src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/TestCase.cs
- src/LiteCore/parse/config_c4.py
- src/LiteCore/parse/templates_c4/C4PredictiveModel.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4PredictiveQuery_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/Common/C4PredictiveQuery_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/Fleece.cs
- src/LiteCore/src/LiteCore.Shared/Interop/ILiteCore.cs
- src/LiteCore/src/LiteCore.Shared/Interop/LiteCore_impl.cs
- src/LiteCore/src/LiteCore.Shared/Interop/LiteCore_shell.cs
- src/LiteCore/src/LiteCore.Shared/Interop/iOS/C4PredictiveQuery_native_ios.cs
- src/LiteCore/src/LiteCore.Shared/Interop/interfacer.ps1
- src/LiteCore/src/LiteCore.Shared/LiteCore.Shared.projitems
The actual implementation will be in the EE repo.
> Implement predictive query feature prerequisites

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
Free SocketFactory context when the Replicator is disposed.
> Free SocketFactory context when the Replicator is disposed.

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
Add ConflictHandlerWhenDocumentIsPurged test and add check to catch not found exception when document does not existed.
> Add ConflictHandlerWhenDocumentIsPurged test

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Document/Blob.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorProgress.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/LiteCore/src/LiteCore.Shared/API/CouchbaseLiteException.cs
Add additional conflict resolver tests: TestConflictResolverWrongDocID, TestConflictResolverReturningBlob, and TestConflictResolverReturningBlobFromDifferentDB
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-net/1164)
> Add additional conflict resolver tests

- src/Couchbase.Lite.Tests.Shared/DocumentTest.cs
Add unit tests for public revision id
> Revision ID tests

- src/Couchbase.Lite/Couchbase.Lite.csproj
- src/LiteCore/src/LiteCore.Shared/Interop/NativeActivate.cs
> CBL-428 Trying to load LiteCore properly

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
CBL-486 Wait for CCR tasks completed before replication status idle callback
> CBL-486 Wait for CCR tasks completed before replication status idle callback

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
CBL-510 Check both remote and local docs are deleted and handle the case. Add unit test to verify.
> CBL-510 Check both remote and local docs are deleted and handle the case.

- src/Couchbase.Lite.Shared/API/Document/Document.cs
- src/Couchbase.Lite.Shared/API/Error/CouchbaseLiteErrorMessage.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
CBL-499 fix RevisionID not null inside push/pull filter
> CBL-499 fix RevisionID not null inside push/pull filter

- src/Couchbase.Lite.Shared/API/Database/Database.cs
CBL-580 Release the fleece document when done using it.
> CBL-580 Release the fleece document when done using it.

- packaging/nuget/couchbase-lite-support-android.nuspec
- packaging/nuget/couchbase-lite-support-ios.nuspec
- packaging/nuget/couchbase-lite-support-netdesktop.nuspec
- packaging/nuget/couchbase-lite-support-uwp.nuspec
- packaging/nuget/couchbase-lite.nuspec
> Update release notes

- src/Couchbase.Lite.Shared/API/Document/Blob.cs
Add release Blob's ContentStream reminder after it's usage
> Add release Blob's ContentStream reminder after it's usage

- src/Couchbase.Lite.Shared/Serialization/FleeceMutableArray.cs
- src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs
Fix of predictive query unit tests and uncomment all the commented predictive unit tests.
> Fix of predictive query unit tests

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/Query/XQuery.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
CBL-774 Enhance Database Close and Delete
Only unit test on live queries, replications tests will be added after replicator are updated base on LiteCore updates.
> CBL-774 Enhance Database Close and Delete

- src/Couchbase.Lite.Shared/API/Error/CouchbaseLiteErrorMessage.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/LiteCoreBridge.cs
- src/LiteCore/src/LiteCore.Shared/Interop/NativeHandler.cs
CBL-450 CBL-451 CBL-452 CBL-453
> Add pending doc ids feature and unit tests

- Jenkinsfile
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
Implement Replicator.Start(reset) and deprecate ResetCheckpoint()
> CBL-939 Implement Replicator.Start(reset), deprecate ResetCheckpoint

- src/Couchbase.Lite.Shared/API/Error/CouchbaseLiteErrorMessage.cs
- src/LiteCore/parse/config_c4.py
- src/LiteCore/parse/parse_structs.py
- src/LiteCore/src/LiteCore.Shared/Interop/C4Listener_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Listener_native.cs
- src/LiteCore/src/LiteCore.Shared/LiteCore.Shared.projitems
> Update c4listener bindings

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Database_native.cs
CBL-992 Implement Database’s performMaintenance(type) feature
> CBL-992 Implement Database’s performMaintenance(type) feature

- src/Couchbase.Lite.Support.NetDesktop/Activate.cs
Since we upgraded to VS2017, ensure that a bundle with the appropriate version is used inferred from the registry key semantics (which are themselves inferred)
> CBL-696: Try to detect the Visual C++ runtime version

- src/Couchbase.Lite.Shared/API/Database/Database.cs
CBL-1250 Adding more detail comments in updated Database Close and Delete APIs.
> CBL-1250 Adding more detail comments in updated Database Close and Delete APIs

- Jenkinsfile
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
CBL-1251 Enable tests, and run iOS pr validation first then android. Add some timeout and dispose replicators before database delete.
> CBL-1251 Enable tests, and run iOS pr validation first then android. Add some timeout and dispose replicators before database delete.

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
CBL-1242 Add TestStopListener to verify the fix that stopping Listener doesn't stop the passive replicator and connections.
> CBL-1242 Add TestStopListener to verify the fix that stopping Listener doesn't stop the passive replicator and connections.

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/Sync/HTTPLogic.cs
- src/Couchbase.Lite.Shared/Sync/WebSocketTransport.cs
- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/LiteCoreBridge.cs
- src/LiteCore/src/LiteCore.Shared/Interop/NativeHandler.cs
> CBL-396 Manage HTTP cookies

- src/Couchbase.Lite.Tests.Shared/P2PTest.cs
Modify Continuous Message Endpoint P2P tests. Increase wait time in condition replicator.Status.Progress.Completed == previousCompleted || replicator.Status.Activity != ReplicatorActivityLevel.Idle fix the test, otherwise count is always greater than 10.
> CBL-1387 Fix continuous Message Endpoint P2P tests. 

- .appveyor/test.ps1
- appveyor.yml
- packaging/nuget/couchbase-lite.nuspec
- src/Couchbase.Lite.Shared/API/DI/Service.cs
- src/Couchbase.Lite.TestCoverage/Couchbase.Lite.TestCoverage.csproj
- src/Couchbase.Lite/Couchbase.Lite.csproj
Update SimpleInjector version to 5+
> CBL-1118 Update SimpleInjector version to 5+

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Document/Blob.cs
- src/Couchbase.Lite.Shared/API/Document/DictionaryObject.cs
- src/Couchbase.Lite.Shared/API/Document/Document.cs
- src/Couchbase.Lite.Shared/API/Document/IJSON.cs
- src/Couchbase.Lite.Shared/API/Error/CouchbaseLiteErrorMessage.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Serialization/MDict.cs
- src/Couchbase.Lite.Tests.Shared/BlobTest.cs
- src/Couchbase.Lite.Tests.Shared/DictionaryTest.cs
- src/Couchbase.Lite.Tests.Shared/DocumentTest.cs
- src/Couchbase.Lite.Tests.Shared/TestCase.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Document+Fleece_native.cs
Add New APIs (Blob.ToJSON, Database.SaveBlob, and Database.GetBlob)
Add tests
> CBL-1681 Blob ToJSON, DB Save Blob and Get Blob CBL-1682 Document ToJSON and test, CBL-1687 Dictionary ToJSON and test

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Base_native.cs
CBL-1565 Ensure c4log_enableFatalExceptionBacktrace is called
> CBL-1565 Ensure c4log_enableFatalExceptionBacktrace is called

- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
CBL-1848 Set default max retry value if it's not already set in replicator config construction.
> CBL-1848 Fix replicator stop retry server re-connection

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
Save Cookie and Get Cookies will now only log error instead of throw exceptions.
> CBL-1909 Save Cookie and Get Cookies will now only log errors.

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Shared/Sync/ReplicatorOptionsDictionary.cs
- src/Couchbase.Lite.Shared/Util/FilteredEvent.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
Passing in progress level via configuration is deprecated; use the setProgressLevel API
> CBL-1905 Use the setProgressLevel API

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Query/N1QLQuery.cs
- src/Couchbase.Lite.Shared/Query/NQuery.cs
- src/Couchbase.Lite.Shared/Query/QueryBase.cs
- src/Couchbase.Lite.Shared/Query/QueryResultSet.cs
- src/Couchbase.Lite.Shared/Query/XQuery.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Query_native.cs
- src/LiteCore/test/LiteCore.Tests.Shared/NestedQueryTest.cs
- src/LiteCore/test/LiteCore.Tests.Shared/QueryTest.cs
- src/LiteCore/test/LiteCore.Tests.Shared/QueryTestBase.cs
* Use new c4query_new2 instead of c4query_new.
* Add CreateQuery method in Database class
> CBL-1790 Create Query with N1QL string

- src/Couchbase.Lite.Shared/Query/DatabaseSource.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
The existing API shouldn't change, so revert test and update the From clause ToJSON.
> CBL-1923 Construct From data source JSON AS db name

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Database_native.cs
- src/LiteCore/test/LiteCore.Tests.Shared/DatabaseTest.cs
Use c4db_deleteNamed, c4db_deleteAtPath deprecated.
c4db_isInTransaction Removal.
Update LiteCore to commit dc8e6cf6adce0088e8fa1edee2d3a999b411d4a0
> More LiteCore deprecated apis

- src/Couchbase.Lite.Support.Android/Activate.cs
- src/Couchbase.Lite.Support.Apple/Activate.cs
- src/Couchbase.Lite.Support.NetDesktop/Activate.cs
- src/Couchbase.Lite.Support.UWP/Activate.cs
Remove obsolete methods Activate(), EnableTextLogging()
> CBL-2154 Update Activate classes

- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
Try catch more host connection exceptions and handle them if any.
> CBL-2186 Check for Network Task IsCompletedSuccessfully and IsFaulted 

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
Add the test to verify the C4DocumentFlag to contain the proper flags during and after conflict resolving.
> CBL-2191 Update HasAttachment flag if doc contains blob during SaveResolvedDocument

- src/LiteCore/src/LiteCore.Shared/Interop/C4Base_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Observer.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Observer_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Query_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/Fleece_native.cs
- src/LiteCore/test/LiteCore.Tests.Shared/ObserverTest.cs
- src/LiteCore/test/LiteCore.Tests.Shared/QueryTest.cs
- src/LiteCore/test/LiteCore.Tests.Shared/QueryTestBase.cs
- bindings addition
- LiteCore bindings .Net tests
> CBL-2282 C4QueryObserver

- .github/workflows/netcore_windows_build_test.yml
- Jenkinsfile
LiteCore to Commit: a24b6f23addc8e9fe71e7d4dff79b91c1563d482 [a24b6f2]
> Update Jenkinsfile & LiteCore

- src/Couchbase.Lite.Shared/Support/SerialQueue.cs
- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
Fix a race in SerialQueue
Add couple verbose logs in the area
> CBL-2897 Fix a race in SerialQueue

- .github/workflows/netcore_windows_build_test.yml
- .github/workflows/uwp_build_test.yml
- src/Couchbase.Lite.Tests.NetCore/Couchbase.Lite.Tests.NetCore.Validation.csproj
- validations/litecore_netcore_build.ps1
> .Net Core GHA update

- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
* Since the cert check if not just checking root cert so change the Error code to TLSCertUntrusted from TLSCertUnknownRoot
* Add manual enhanced pinned server certificate feature tests
> CBL-2975 Tests enhanced pinned server certificate feature (3.0.2)

- .github/workflows/netcore_windows_build_test.yml
- .github/workflows/uwp_build_test.yml
- packaging/nuget/couchbase-lite-support-netdesktop.nuspec
- packaging/nuget/couchbase-lite.nuspec
- src/Couchbase.Lite.Shared/Support/netdesktop/DefaultDirectoryResolver.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/DesktopConsoleLogger.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/LinuxProxy.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/MacProxy.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/WindowsProxy.cs
- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
- src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj
- src/Couchbase.Lite.Tests.NetCore/Couchbase.Lite.Tests.NetCore.Validation.csproj
- src/Couchbase.Lite.Tests.Shared/CSharpTest.cs
- src/Couchbase.Lite.Tests.Shared/LogTest.cs
- src/Couchbase.Lite.Tests.Shared/PerfTest.cs
- src/Couchbase.Lite.Tests.Shared/TestCase.cs
- src/Couchbase.Lite/Couchbase.Lite.csproj
- src/LiteCore/test/LiteCore.Tests.Shared/Test.cs
- src/global.json
- validations/litecore_netcore_build.ps1
- validations/litecore_uwp_build.ps1
Update LiteCore to Commit: b807f0371e01bb76a0a5912464eb49ff0a87d0d7 [b807f03] (CBL-3051)
> Net 6 support update

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Database/DatabaseChangedEventArgs.cs
- src/Couchbase.Lite.Shared/API/Database/Interfaces/IChangeObservable.cs
- src/Couchbase.Lite.Shared/API/Database/Interfaces/ICollection.cs
- src/Couchbase.Lite.Shared/API/Database/Interfaces/IScope.cs
- src/Couchbase.Lite.Shared/API/Database/ListenerToken.cs
- src/Couchbase.Lite.Shared/API/Database/Scope.cs
- src/Couchbase.Lite.Shared/API/Document/Document.cs
- src/Couchbase.Lite.Shared/API/Query/DataSource.cs
- src/Couchbase.Lite.Shared/API/Query/IIndexable.cs
- src/Couchbase.Lite.Shared/API/Query/IQuery.cs
- src/Couchbase.Lite.Shared/API/Query/IQueryFactory.cs
- src/Couchbase.Lite.Shared/API/Sync/BasicAuthenticator.cs
- src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorProgress.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorStatusChangedEventArgs.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Query/DatabaseSource.cs
- src/Couchbase.Lite.Shared/Query/LiveQuerier.cs
- src/Couchbase.Lite.Shared/Query/QueryBase.cs
- src/Couchbase.Lite.Shared/Util/FilteredEvent.cs
- src/Couchbase.Lite.Tests.Shared/NotificationTest.cs
- src/Couchbase.Lite.Tests.Shared/P2PTest.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
- Database, Document, Query
- Replicator Configuration
- ListenerToken Remove() - [CBL-1762](https://issues.couchbase.com/browse/CBL-1762)
***** Not all API comments are updated *****
> CBL-3058 Scopes and Collections Prototype

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorProgress.cs
- src/LiteCore/binding_list/c4.def
- src/LiteCore/binding_list/c4_ee.def
- src/LiteCore/parse/templates_c4/C4ReplicationCollection.cs
- src/LiteCore/parse/templates_c4/C4ReplicatorParameters.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4DocumentTypes_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Listener_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4ReplicatorTypes_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
C4CollectionSpec property addition in C4DocumentEnded
> CBL-3197 More Scope Collection bindings update

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Document/ArrayObject.cs
- src/Couchbase.Lite.Shared/API/Document/DictionaryObject.cs
- src/Couchbase.Lite.Shared/API/Document/Document.cs
- src/Couchbase.Lite.Shared/API/Document/MutableDocument.cs
- src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/Document/DocContext.cs
- src/Couchbase.Lite.Shared/Query/DatabaseSource.cs
- src/Couchbase.Lite.Shared/Query/From.cs
- src/Couchbase.Lite.Shared/Query/QueryBase.cs
- src/Couchbase.Lite.Shared/Query/QueryResultContext.cs
- src/Couchbase.Lite.Shared/Query/QueryResultSet.cs
- src/Couchbase.Lite.Shared/Query/XQuery.cs
- src/Couchbase.Lite.Shared/Serialization/FLValueConverter.cs
- src/Couchbase.Lite.Tests.Shared/CSharpTest.cs
- src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/Couchbase.Lite.Tests.Shared/DocumentTest.cs
- src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
- src/Couchbase.Lite.Tests.Shared/TestCase.cs
- src/LiteCore/test/LiteCore.Tests.Shared/ScopeCollectionTest.cs
- Add Collection APIs that are deprecated in Database class
> CBL-3226 Collection Implementation

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Database/DatabaseChangedEventArgs.cs
- src/Couchbase.Lite.Shared/API/Database/DocumentChangedEventArgs.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
CBL-3332 Remove post changes after finishing InBatch call
Update/add missing Scopes Collections APIs comments and annotations
> CBL-3332 Remove post changes after finishing InBatch call & Update  Scopes Collections APIs

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/NotificationTest.cs
- src/Couchbase.Lite.Tests.Shared/P2PTest.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopesCollections.QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4ReplicatorTypes_defs.cs
Collection Replication Configuration update to adapt Push/Pull/PushFilter/PullFilter removal from Replicator level configuration.
Tests were removed awaiting for later LiteCore updates, especially waiting for fixes from this LiteCore commit [Collection Replication Configuration update ](https://github.com/couchbase/couchbase-lite-core/commit/05dc78bf84662cdc671d53710499ee9864b9aa25)
> CBL-3511 Collection Replication Configuration update with latest LiteCore change (Build 198)

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorProgress.cs
- src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/NotificationTest.cs
- src/Couchbase.Lite.Tests.Shared/P2PTest.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
Update LiteCore to Commit: 4b4b513579e35b78ff70d616d0c6886100a76c96 [4b4b513]
Enable temp disabled tests
Support conflict resolver and fix collection/scope names in ReplicatedDocument
CBL-3344 Scopes Collections Replication tests
> CBL-3491 Update LiteCore (build 214) and enable legacy tests CBL-3344 Scopes Collections Replication tests

- src/Couchbase.Lite.Tests.Shared/DocumentTest.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopesCollections.QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/TestCase.cs
Update LiteCore to Commit: 28756695b85a61b19781d74a0336d4f211002acd [2875669] (3.1.0-225)
CBL-3627 Scopes Collections SQL++ Query Tests and QueryBuilder Tests
> CBL-3627 Scopes Collections SQL++ Query Tests and QueryBuilder Tests

- packaging/nuget/couchbase-lite-support-android.nuspec
- packaging/nuget/couchbase-lite-support-ios.nuspec
- packaging/nuget/couchbase-lite-support-netdesktop.nuspec
- packaging/nuget/couchbase-lite-support-uwp.nuspec
- packaging/nuget/couchbase-lite.nuspec
- src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj
- src/Couchbase.Lite.Support.Apple/iOS/Couchbase.Lite.Support.iOS.csproj
- src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj
- src/Couchbase.Lite.Support.UWP/Couchbase.Lite.Support.UWP.csproj
- src/Couchbase.Lite.sln
- src/Couchbase.Lite/Couchbase.Lite.csproj
- src/build/do_fetch_litecore.ps1
All nuspec files are built successfully. 
Only issue is not getting LiteCore-Debug.framework from debug build.
> Fix nuget packaging

- src/Couchbase.Lite.Tests.Shared/ArrayTest.cs
- src/Couchbase.Lite.Tests.Shared/BlobTest.cs
- src/Couchbase.Lite.Tests.Shared/FragmentTest.cs
- src/Couchbase.Lite.Tests.Shared/PredictiveQueryTest.cs
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
- src/Couchbase.Lite.Tests.Shared/TestCase.cs
- src/Couchbase.Lite/Couchbase.Lite.csproj
Fix Maui WinUI tests by fix issues after FluentAssertions update
Fix condition in CBL csproj
Update LiteCore to Commit: 2f3397837e884a37d28b2b2ee80326938a4352a0 [2f33978] build 3.1-254
> CBL-3681 Fix Maui WinUI tests

- src/Couchbase.Lite.Tests.Shared/TestCase.cs
- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
- src/global.json
EE PR: https://github.com/couchbaselabs/couchbase-lite-net-ee/pull/82
> CBL-3818 Fix UrlEndpointListener's Urls is 0 after listener started in android

- .gitignore
- packaging/nuget/do_package.ps1
- src/Couchbase.Lite.Support.Android/Couchbase.Lite.Support.Android.csproj
- src/Couchbase.Lite.Support.Apple/iOS/Couchbase.Lite.Support.iOS.csproj
- src/Couchbase.Lite.Support.NetDesktop/Couchbase.Lite.Support.NetDesktop.csproj
- src/Couchbase.Lite.Support.UWP/Couchbase.Lite.Support.UWP.csproj
- src/Couchbase.Lite.Support.WinUI/Couchbase.Lite.Support.WinUI.csproj
- src/Couchbase.Lite/Couchbase.Lite.csproj
Modify the package script to generate snupkg files in addition to nupkg.  After some infrastructure changes, this will result in CE being compatibile with nuget source server.
> CBL-3902: Upgrade to official Microsoft SourceLink

- src/Couchbase.Lite.Shared/API/Info/Constants.cs
- src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Shared/Sync/ReplicatorOptionsDictionary.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopesCollections.ReplicationTest.cs
CBL-3764 CBL-3768 Enhanced default values in Replicator Configuration and Collection Configuration
And modify tests to verify the update
> CBL-3764 CBL-3768 Enhanced default values in ReplicatorConfiguration and CollectionConfiguration

- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
- src/LiteCore/src/LiteCore.Shared/API/CouchbaseLiteException.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Error_defs.cs
Validate the change with these tests in this PR: https://github.com/couchbase/couchbase-lite-net/pull/1379
> CBL-3918 Report invalid / unknown network interface using kC4NetErrUnknownInterface

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
The previous ones were a bit sparse
> CBL-3977: Update Replicator.Stop API docs

- src/Couchbase.Lite.Shared/API/Query/Expression.cs
- src/Couchbase.Lite.Shared/API/Query/FullTextFunction.cs
- src/Couchbase.Lite.Shared/API/Query/IFullTextIndexExpression.cs
- src/Couchbase.Lite.Shared/API/Query/IIndexExpression.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/QueryTest.cs
Note that there is a commented section that is blocked by 3994.
> CBL-4010: Expression.FullTextIndex API for FTS queries

- src/Couchbase.Lite.Shared/API/Sync/CollectionConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
Add more detail API comment on Channels in CollectionConfiguration and ReplicatorConfiguration.
> Add additional API comment on Channels.

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/Query/NQuery.cs
- src/Couchbase.Lite.Shared/Query/XQuery.cs
And output this description when things are taking a long time to stop
> Add a more detailed string override for query classes

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Info/Constants.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Shared/Sync/ReplicatorOptionsDictionary.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
Bump LiteCore to a higher version that that API changes in
> CBL-4123: Add AcceptParentDomainCookies to ReplicatorConfiguration

- src/Couchbase.Lite.Shared/Support/netdesktop/MacProxy.cs
The CFNetwork framework has been moved to /System/Library/Frameworks/ in macOS Ventura. A fallback has been implemented to support both paths.
> macos: fix MacProxy initialization in >= Ventura

- packaging/nuget/couchbase-lite-support-android.nuspec
- packaging/nuget/couchbase-lite-support-ios.nuspec
- packaging/nuget/couchbase-lite-support-netdesktop.nuspec
- packaging/nuget/couchbase-lite-support-uwp.nuspec
- packaging/nuget/couchbase-lite-support-winui.nuspec
- packaging/nuget/couchbase-lite.nuspec
- src/Couchbase.Lite.Shared/API/DI/Service.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Shared/Support/Android/XEReachability.cs
- src/Couchbase.Lite.Shared/Support/UWP/DefaultDirectoryResolver.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/DefaultDirectoryResolver.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/DesktopConsoleLogger.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/LinuxProxy.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/MacProxy.cs
- src/Couchbase.Lite.Shared/Support/netdesktop/WindowsProxy.cs
- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
- src/Couchbase.Lite/Couchbase.Lite.csproj
> CBL-4170: Use Xamarin essentials for network reachability

- src/Couchbase.Lite.Shared/Support/netdesktop/MacProxy.cs
CFNetwork changed locations in macOS 13
> CBL-4273: Fix MacProxy to account for native library path changes

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Document/MutableArrayObject.cs
- src/Couchbase.Lite.Shared/API/Info/Defaults.cs
- src/Couchbase.Lite.Shared/API/Query/IQuery.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/LiteCore/src/LiteCore.Shared/API/CouchbaseLiteException.cs
> CBL-4479: Clean up badly formatted XML docs

- src/Couchbase.Lite.Tests.Shared/URLEndpointListenerTest.cs
Add some test stability stuff in as a bonus
> Update to LiteCore 3.1.1-9

- src/Couchbase.Lite/Couchbase.Lite.csproj
net7.0-android31 -> net7.0-android33
> CBL-4679: Correct Android version in CE project

- packaging/nuget/couchbase-lite.nuspec
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/Query/QueryBase.cs
- src/Couchbase.Lite.Shared/Support/SerialQueue.cs
- src/Couchbase.Lite.Shared/Sync/WebSocketWrapper.cs
- src/Couchbase.Lite.Shared/Util/FilteredEvent.cs
- src/Couchbase.Lite.Tests.Shared/CSharpTest.cs
- src/Couchbase.Lite/Couchbase.Lite.csproj
Remove the modified one from our codebase
> CBL-4720: Use SerialQueue from nuget packages

- README.md
- packaging/nuget/README.md
- packaging/nuget/couchbase-lite-support-android.nuspec
- packaging/nuget/couchbase-lite-support-ios.nuspec
- packaging/nuget/couchbase-lite-support-netdesktop.nuspec
- packaging/nuget/couchbase-lite-support-uwp.nuspec
- packaging/nuget/couchbase-lite-support-winui.nuspec
- packaging/nuget/couchbase-lite.nuspec
https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/
> CBL-4834: Add README to nuget package

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
Implement a property in the Collection class that returns the collection full name in < scope-name >.< collection-name > format.
> CBL-5204 : Collection's FullName Property

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Shared/API/Database/Scope.cs
- src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
Implement Scope's and Collection's Database Property.
> CBL-5210 : Scope's and Collection's Database Property

- src/Couchbase.Lite.Shared/API/Query/ValueIndexConfiguration.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
Add a test to assure that is the case
> CBL-5312: Correct ValueIndexConfiguration to actually make ValueIndex

- src/Couchbase.Lite.Shared/API/Query/ValueIndexConfiguration.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
Add a test to assure that is the case.  Ported from ab75d7af590b883c213c7d33cb9fa502a049eb21
> CBL-5313: Correct ValueIndexConfiguration to actually make ValueIndex

- packaging/nuget/do_package.ps1
- src/build/do_build.ps1
The old Get-Cim is now unreliable it seems.
> Use vswhere.exe to locate visual studio

- src/build/do_build.ps1
- src/global.json
And also make sure we continue building this line with the .NET 6.0.x SDK
> CBL-5430: Make Visual Studio search more reliable

- src/Couchbase.Lite.Shared/API/Document/ArrayObject.cs
- src/Couchbase.Lite.Shared/API/Info/Defaults.cs
- src/Couchbase.Lite.Shared/Serialization/FleeceMutableArray.cs
Here is it just a couple constants, since all the logic is EE.
Side: FleeceMutableArray null handling
> CBL-5505: Re-enable Vector Search functionality

- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/Couchbase.Lite.Shared/Query/IndexConfiguration.cs
In service of validating a vector index configuration
> Add in a method to validate index configuration

- src/Couchbase.Lite.Shared/Query/LiveQuerier.cs
Otherwise this class will live forever as a memory leak.  Also tighten up the disposal protections on this class.
Needed changes to bring it inline, but this is the equivalent of #1615
> CBL-5649: Dispose the context handle of LiveQuerier

- src/Couchbase.Lite.Shared/Query/LiveQuerier.cs
Otherwise this class will live forever as a memory leak.  Also tighten up the disposal protections on this class.
> CBL-5648: Dispose the context handle of LiveQuerier

- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
Indicating that it may not be called inside of InBatch
> CBL-5713: Add note to Replicator.Start

- core_version.ini
- src/LiteCore/binding_list/c4.def
- src/LiteCore/parse/parse_structs.py
- src/LiteCore/src/LiteCore.Shared/Interop/C4Collection_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Database_native.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Index_native.cs
Use the new LiteCore API to return some early error information about it.
> CBL-5857: Rename Extension.Load to Extension.Enable

- core_version.ini
- src/Couchbase.Lite.Shared/API/Database/Collection.cs
- src/LiteCore/binding_list/c4.def
- src/LiteCore/src/LiteCore.Shared/Interop/C4IndexTypes_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/C4Index_native.cs
> Stop using iOS unexported method for index is trained

- src/Couchbase.Lite.Shared/Query/NQuery.cs
- src/Couchbase.Lite.Shared/Query/XQuery.cs
- src/Couchbase.Lite.Tests.Shared/ConcurrencyTest.cs
Manually ported from https://github.com/couchbase/couchbase-lite-net/pull/1652
Changes are pretty small though so the diff should look very similar
> CBL-6129: Queries need to use database lock for most operations

- src/Couchbase.Lite.Tests.Shared/CSharpTest.cs
Some of the needed API is only exposed for debug builds
> Turn off wrapper tests in release

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Database/DatabaseConfiguration.cs
- src/Couchbase.Lite.Shared/API/Info/Defaults.cs
- src/Couchbase.Lite.Tests.Shared/Couchbase.Lite.Tests.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/MmapTest.cs
- src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs
- src/Couchbase.Lite.Tests.Shared/Util/ImplementsTestSpecAttribute.cs
- src/LiteCore/src/LiteCore.Shared/Interop/FLBase_defs.cs
- src/LiteCore/src/LiteCore.Shared/Interop/Fleece.cs
Also
- Support for tool based test spec verification (ImplementsTestSpecAttribute)
> CBL-6325: Implement MmapEnabled property on DatabaseConfiguration

- src/Couchbase.Lite.Tests.Shared/LogTest.cs
- src/Couchbase.Lite.Tests.Shared/Util/WaitAssert.cs
- ConcurrencyTests using WaitHandle.WaitAll have issues with .NET 4.6.2, so use a homegrown method of waiting for multiple things for an overall period of time
- LogTest TestMaxSize was failing because the directory of logs was not being deleted between variants
- LogTest TestPlaintestLoggingLevels was failing because somehow other (legitimate) logs were making their way into the log files and throwing off the overall count.  Use a more robust system of checking that they contain two meta log lines at the beginning, and then search for the exact number of lines emitted by the test (while ignoring lines not emitted by the test)
> Found and fixed some flakiness in tests

- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Database/DatabaseConfiguration.cs
- src/Couchbase.Lite.Shared/API/Sync/BackgroundMonitor.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator+Backgrounding.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Shared/API/Sync/ReplicatorConfiguration.cs
- src/Couchbase.Lite.Shared/Couchbase.Lite.Shared.projitems
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs
- src/LiteCore/binding_list/c4.def
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native.cs
Also, uncomment the commented out DiskFullSync logic now that LiteCore has the relevant flags available
> CBL-6544: Implement background awareness for iOS 

- Jenkinsfile
- src/Couchbase.Lite.Shared/API/Sync/Replicator+Backgrounding.cs
- src/Couchbase.Lite.Shared/API/Sync/Replicator.cs
- src/Couchbase.Lite.Support.WinUI/Couchbase.Lite.Support.WinUI.csproj
- src/LiteCore/src/LiteCore.Shared/Interop/C4Replicator_native_safe.cs
Add more steps to PR validation to catch this issue
> Fix compilation error for .NET iOS

- core_version.ini
- src/Couchbase.Lite.Support.NetDesktop/Activate.cs
Revert change to required c++ library
> Update LiteCore to 3.2.3-10

- src/Couchbase.Lite.Tests.NetCore/Couchbase.Lite.Tests.NetCore.csproj
I really need a more unified way of doing this....
> Update postbuild testing to .NET 8

- Jenkinsfile
- src/Couchbase.Lite.Shared/API/Database/Database.cs
- src/Couchbase.Lite.Shared/API/Document/Blob.cs
- src/Couchbase.Lite.Tests.Shared/DatabaseTest.cs
- src/Couchbase.Lite.Tests.Shared/ReplicationTest.cs
- src/Couchbase.Lite.Tests.Shared/SQLiteOptionsTest.cs
- src/Couchbase.Lite.Tests.Shared/ScopeCollectionTest.cs
Instead of InvalidOperationException
> CBL-7416: Throw CouchbaseLiteException when db not open
